routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    return view('welcome');
});

Route::resource('libro', App\Http\Controllers\LibroController::class);

Route::resource('gato', App\Http\Controllers\GatoController::class);

app/Models/Gato.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gato extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'age',
        'breed',
        'comments'
    ];
}

app/Models/Libro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'author',
        'genre',
        'isbn',
        'synopsis'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GatoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gato;
use Illuminate\Http\Request;

class GatoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $gatos = Gato::Paginate(5);
        return view('gato.index')->with('gatos', $gatos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('gato.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:20',
            'age' => 'required|lte:99',
            'breed' => 'required|max:20'
        ]);

        $gato = Gato::create($request->only('name', 'age', 'breed', 'comments'));
        return redirect()->route('gato.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Gato  $gato
     * @return \Illuminate\Http\Response
     */
    public function show(Gato $gato)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Gato  $gato
     * @return \Illuminate\Http\Response
     */
    public function edit(Gato $gato)
    {
        return view('gato.form')->with('gato', $gato);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Gato  $gato
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Gato $gato)
    {
        $request->validate([
            'name' => 'required|max:20',
            'age' => 'required|lte:99',
            'breed' => 'required|max:20'
        ]);

        $gato->name = $request['name'];
        $gato->age = $request['age'];
        $gato->breed = $request['breed'];
        $gato->comments = $request['comments'];
        $gato->save();

        return redirect()->route('gato.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Gato  $gato
     * @return \Illuminate\Http\Response
     */
    public function destroy(Gato $gato)
    {
        $gato->delete();
        return redirect()->route('gato.index');
    }
}

app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Libro;
use Illuminate\Http\Request;

class LibroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $libros = Libro::Paginate(5);
        return view('libro.index')->with('libros', $libros);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('libro.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:20',
            'author' => 'required|max:20',
            'isbn' => 'required|max:13|min:10'
        ]);

        $libro = Libro::create($request->only('title', 'author', 'genre', 'isbn', 'synopsis'));
        return redirect()->route('libro.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function show(Libro $libro)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function edit(Libro $libro)
    {
        return view('libro.form')->with('libro', $libro);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Libro $libro)
    {
        $request->validate([
            'title' => 'required|max:20',
            'author' => 'required|max:20',
            'isbn' => 'required|max:13|min:10'
        ]);

        $libro->title = $request['title'];
        $libro->author = $request['author'];
        $libro->genre = $request['genre'];
        $libro->isbn = $request['isbn'];
        $libro->synopsis = $request['synopsis'];
        $libro->save();

        return redirect()->route('libro.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Libro  $libro
     * @return \Illuminate\Http\Response
     */
    public function destroy(Libro $libro)
    {
        $libro->delete();
        return redirect()->route('libro.index');
    }
}

resources/views/gato/form.blade.php
@extends('../theme/base')

@section('contingut')
<div class="container py-5 text-center">
    @if(isset($gato))
    <h1>Editar datos del gato</h1>
    @else
    <h1>Añadir nuevo gato</h1>
    @endif

    @if(isset($gato))
    <form action="{{route('gato.update', $gato)}}" method="post">
        @method('PUT')
    @else        
    <form action="{{ route('gato.store')}}" method="post">
    @endif

        @csrf
        <div class="my-3 text-start">
            <label for="name" class="form-label">Nombre</label>
            <input type="text" name="name" class="form-control" placeholder="Nombre" value="{{old('name') ?? @$gato->name}}">
            @error('name')
                    <p class="form-text text-danger">{{$message}}</p>
            @enderror
        </div>
        <div class="row">
            <div class="my-3 text-start col-12 col-md-6">
                <label for="age" class="form-label">Edad</label>
                <input type="number" name="age" class="form-control" placeholder="Edad del gato" step="0,01" value="{{old('age') ?? @$gato->age}}">
                @error('age')
                        <p class="form-text text-danger">{{$message}}</p>
                @enderror
            </div>
            <div class="my-3 text-start col-12 col-md-6">
                <label for="breed" class="form-label">Raza</label>
                <input type="text" name="breed" class="form-control" placeholder="Raza del gato" value="{{old('breed') ?? @$gato->breed}}">
                @error('breed')
                        <p class="form-text text-danger">{{$message}}</p>
                @enderror
            </div>
        </div>
        <div class="my-3 text-start">
            <label for="comments" class="form-label">Comentarios</label>
            <textarea name="comments" cols="30" rows="5" class="form-control" placeholder="Comentarios del gato, su personalidad, características...">{{old('comments') ?? @$gato->comments}}</textarea>
            @error('comments')
                <p class="form-text text-danger">{{$message}}</p>
            @enderror
        </div>

        @if(isset($gato))
        <button type="submit" class="btn btn-brown">Editar gato</button>
        @else
        <button type="submit" class="btn btn-brown">Añadir gato</button>
        @endif
        <a href="{{ route('gato.index')}}" class="btn btn-danger">Cancelar</a>
    </form>
</div>
@stop

resources/views/gato/index.blade.php
@extends('../theme/base')

@section('contingut')
    <div class="container text-center mt-5">
        <h1>Lista de gatos</h1>
        <a href="{{ route('gato.create')}}" class="btn btn-brown">Añadir gato</a>

        <table class="table border-brown my-5">
            <thread>
                <th>Nombre</th>
                <th>Edad</th>
                <th>Raza</th>
                <th>Acciones</th>
            </thread>
            <tbody>
                @forelse($gatos as $item)
                <tr>
                    <td>{{$item->name}}</td>
                    <td>{{$item->age}}</td>
                    <td>{{$item->breed}}</td>
                    <td>
                        <a href="{{route('gato.edit', $item)}}" class="btn btn-warning">Editar <img src="{{ asset('/images/icons8-edit-50.png') }}" class="ps-1" style="height: 20px;"></a>
                        <form action="{{ route('gato.destroy', $item) }}" method="post" class="d-inline">
                            @method('DELETE')
                            @csrf
                            <button type="submit" onclick='return confirm("¿Seguro que quieres eliminar el gato?")' class="btn btn-danger">Eliminar <img src="{{ asset('/images/icons8-trash-50.png') }}" class="ps-1" style="height: 20px;"></button>
                        </form>
                    </td>
                </tr>
                
                @empty
                <td colspan="4">Actualmente no hay gatos registrados</td>
                @endforelse
            </tbody>
        </table>
        {{$gatos->links("pagination::bootstrap-4")}}
    </div>
    
@stop

resources/views/libro/form.blade.php
@extends('../theme/base')

@section('contingut')
<div class="container py-5 text-center">
    @if(isset($libro))
    <h1>Editar libro</h1>
    @else
    <h1>Añadir libro</h1>
    @endif

    @if(isset($libro))
    <form action="{{route('libro.update', $libro)}}" method="post">
        @method('PUT')
    @else        
    <form action="{{ route('libro.store')}}" method="post">
    @endif

        @csrf
        <div class="my-3 text-start">
            <label for="title" class="form-label">Título</label>
            <input type="text" name="title" class="form-control" placeholder="Título del libro" value="{{old('title') ?? @$libro->title}}">
            @error('title')
                    <p class="form-text text-danger">{{$message}}</p>
            @enderror
        </div>
        <div class="my-3 text-start">
            <label for="author" class="form-label">Autor/autora</label>
            <input type="text" name="author" class="form-control" placeholder="Autor/autora del libro" value="{{old('author') ?? @$libro->author}}">
            @error('author')
                    <p class="form-text text-danger">{{$message}}</p>
            @enderror
        </div>
        <div class="row">
            <div class="my-3 col-12 col-md-6 text-start">
                <label for="genre" class="form-label">Género</label>
                <input type="text" name="genre" class="form-control" placeholder="Género del libro" value="{{old('genre') ?? @$libro->genre}}">
                @error('author')
                        <p class="form-text text-danger">{{$message}}</p>
                @enderror
            </div>
            <div class="my-3 col-12 col-md-6 text-start">
                <label for="isbn" class="form-label">ISBN</label>
                <input type="number" name="isbn" class="form-control" placeholder="ISBN" step="0,01" value="{{old('isbn') ?? @$libro->isbn}}">
                @error('isbn')
                        <p class="form-text text-danger">{{$message}}</p>
                @enderror
            </div>
        </div>
        <div class="my-3 text-start">
            <label for="synopsis" class="form-label">Sinopsis</label>
            <textarea name="synopsis" cols="30" rows="5" class="form-control" placeholder="Sinopsis del libro">{{old('synopsis') ?? @$libro->synopsis}}</textarea>
            @error('synopsis')
                <p class="form-text text-danger">{{$message}}</p>
            @enderror
        </div>

        @if(isset($libro))
        <button type="submit" class="btn btn-brown">Editar libro</button>
        @else
        <button type="submit" class="btn btn-brown">Añadir libro</button>
        @endif
        <a href="{{ route('libro.index')}}" class="btn btn-danger">Cancelar</a>
    </form>
</div>
@stop

resources/views/libro/index.blade.php
@extends('../theme/base')

@section('contingut')
    <div class="container text-center mt-5">
        <h1>Lista de libros disponibles</h1>
        <a href="{{ route('libro.create')}}" class="btn btn-brown">Añadir libro</a>

        <table class="table border-brown my-5">
            <thread>
                <th>Título</th>
                <th>Autor</th>
                <th>Género</th>
                <th>Acciones</th>
            </thread>
            <tbody>
                @forelse($libros as $item)
                <tr>
                    <td>{{$item->title}}</td>
                    <td>{{$item->author}}</td>
                    <td>{{$item->genre}}</td>
                    <td>
                        <a href="{{route('libro.edit', $item)}}" class="btn btn-warning">Editar <img src="{{ asset('/images/icons8-edit-50.png') }}" class="ps-1" style="height: 20px;"></a>
                        <form action="{{ route('libro.destroy', $item) }}" method="post" class="d-inline">
                            @method('DELETE')
                            @csrf
                            <button type="submit" onclick='return confirm("¿Seguro que quieres eliminar el libro?")' class="btn btn-danger">Eliminar <img src="{{ asset('/images/icons8-trash-50.png') }}" class="ps-1" style="height: 20px;"></button>                        
                        </form>
                    </td>
                </tr>
                @empty
                <td colspan="4">Actualmente no hay libros registrados</td>
                @endforelse
            </tbody>
        </table>
        {{$libros->links("pagination::bootstrap-4")}}
    </div>
    
@stop

resources/views/theme/base.blade.php
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <link href="{{ asset('/css/style.css') }}" rel="stylesheet">

  <title>Gatoteca - Javier Romero</title>
</head>

<body class="bg-cream">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-ocre">
      <div class="container-fluid">
        <a class="navbar-brand logo" href="/"><img src="https://images.squarespace-cdn.com/content/v1/61583236df8ffd37e403bb6c/a33d27eb-c5eb-4d5b-8252-1b9d044ef380/logo+gatoteca_completo.png?format=1500w" alt="" style="height: 50px;"></a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-btn" href="{{ route('gato.index')}}">Gatos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link nav-btn" href="{{ route('libro.index')}}">Libros</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <section class="main">
  @yield('contingut')
  </section>

  @yield('footer')

</body>

</html>